[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-linter"
version = "0.1.0"
requires-python = ">=3.11"

[project.optional-dependencies]
dev = ["flake8"]

[tool.setuptools]
py-modules = []